version: "3.9"
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: app
            RABBITMQ_DEFAULT_PASS: app
            RABBITMQ_DEFAULT_VHOST: /
        ports: ["5672:5672", "15672:15672"]
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 20s
        restart: unless-stopped
    proposal-sql:
        container_name: proposal-sql
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
            - MSSQL_SA_PASSWORD=Str0ng!Passw0rd#
        ports: ["14333:1433"]
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Str0ng!Passw0rd#", "-Q", "SELECT 1", "-C"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s
        volumes:
            - proposal_sql_data:/var/opt/mssql
    contract-sql:
        container_name: contract-sql
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
            - MSSQL_SA_PASSWORD=Str0ng!Passw0rd#
        ports: ["14334:1433"]
        healthcheck:
            test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Str0ng!Passw0rd#", "-Q", "SELECT 1", "-C"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s
        volumes:
            - contract_sql_data:/var/opt/mssql
    proposal-api:   
        container_name: proposal-api
        build: 
            context: .                                  
            dockerfile: ProposalService/Proposal.Infrastructure/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports: ["8080:8080"]
        depends_on:
            rabbitmq:
                condition: service_healthy
            proposal-sql:
                condition: service_healthy
    contract-api:
        container_name: contract-api
        build: 
            context: .
            dockerfile: ContractService/Contract.Infrastructure/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports: ["8081:8080"]
        depends_on:
            rabbitmq:
                condition: service_healthy
            contract-sql:
                condition: service_healthy
volumes:
    proposal_sql_data:
    contract_sql_data: